name: FantasyWorld
version: '${version}'

main: me.KazXeno.fantasyWorld.FantasyWorld
api-version: '1.20'
load: POSTWORLD

commands:
  testcombat:
    description: Combat test command
    usage: /testcombat <BaseDamage> <Scaling> <DamageType> <CritChance> <CritDamage> <Defense> <Penetration> <DamageReduction> <Lifesteal>
  stats:
    description: Show player stats
    usage: /stats
  cast:
    description: Cast a skill
    usage: /cast <skill_id>
  getitem:
    description: Open custom item browser
    usage: /getitem
  setrace:
    description: Set player race
    usage: /setrace <race>
  setclass:
    description: Set player class
    usage: /setclass <class>