name: FantasyWorld
version: '${version}'

main: me.KazXeno.fantasyWorld.FantasyWorld
api-version: '1.20'
load: POSTWORLD

commands:
  testcombat:
    description: Combat test command
    usage: /testcombat <BaseDamage> <Scaling> <DamageType> <CritChance> <CritDamage> <Defense> <Penetration> <DamageReduction> <Lifesteal>
  stats:
    description: Show player stats
    usage: /stats